### ISSUE TITLE
Support travis-ci.com endpoint

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/travis#77] opened 2018-07-21 07:12 UTC
Need to double-check what it means if a repository has been signed up with travis-ci.com. Does API access work transparently?

Docs on Travis: https://docs.travis-ci.com/user/open-source-on-travis-ci-com/.

https://github.com/ropensci/dev_guide/issues/45

**Comment by krlmlr** [comment] 2018-10-03 20:42
This now has priority, because I can no longer register new repos on travis-ci.org. Unfortunately, I don't see yet how to obtain a Travis token programmatically :-(

**Comment by krlmlr** [comment] 2018-10-03 21:14
Working on my machine now, will double-check tomorrow. Unfortunately, now the `"repo"` scope seems to be required to interact with the API...

**Comment by krlmlr** [comment] 2018-11-02 21:06
I have a partial implementation, still needs testing.

**Comment by maelle** [comment] 2019-01-16 12:03
:wave: @krlmlr, what the status on this?

**Comment by krlmlr** [comment] 2019-01-16 12:18
It's a big mess. I'll experiment with a separate _travis.com_ package before we can decide how to handle this.

**Comment by krlmlr** [comment] 2019-01-27 08:57
It also feels like travis-ci.org will stay around for some time, even if GitHub Services will be shut down. (I mistakenly assumed that shutdown of GH Services means the end of .org.)

Need to make the package work smoothly with .org (again) and at the same time investigate a _travis.com_ package.

**Comment by pat-s** [comment] 2019-02-25 16:02
We also faced this error today. Took me quite some time to trace back:

1. `tic::prepare_all_stages()` is missing the preparation of `step_build_pkgdown`
2. The reason is that the env var `id_rsa` is missing in the Travis repo
3. It is missing because `travis::use_travis_deploy()` does not support the Travis.com endpoint

Maybe we should put this into the README until the issue is solved.

**Comment by maelle** [comment] 2019-03-05 10:29
is it .com for private repositories and .org for public repositories or is it more complicated than this?

**Comment by maelle** [comment] 2019-03-05 10:31
Probably more complicated :thinking: https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com

**Comment by llrs** [comment] 2019-11-23 18:25
For the record, I had a public repository that got into travis-ci.com and keeps asking me for use_travis_deploy:

> Error: No deploy key found, please setup with `travis::use_travis_deploy()`

I am using travis 0.2.11.9001.

**Comment by pat-s** [comment] 2019-11-23 18:29
Support for the com endpoint is available for testing in the "travis-com" branch.

Master does not support it yet.

**Comment by joethorley** [comment] 2019-12-07 22:07
Hi @krlmlr 

When I install this branch and run
```
travis::use_travis_deploy(endpoint = ".com")
```
I get 
```
Env var 'R_TRAVIS' not set by user. Defaulting to '.org' endpoint.
```
which seems an error given that endpoint was explicitly set to be ".com"

If I then set `R_TRAVIS = .com` in my `.RProfile file` I get
```
travis: Using Travis endpoint '.com' set via env var `R_TRAVIS`.
Querying Github deploy keys from repo.
✔ Setting active project to '/Users/joe/Code/term/term'
Deploy key for Travis CI .com already present. No action required.
```

**Comment by joethorley** [comment] 2019-12-08 00:00
And when I run with `R_TRAVIS = .com` in my .RProfile file on a project without an existing deploy key I get.
```r
> travis::use_travis_deploy(endpoint = ".com")
travis: Using Travis endpoint '.com' set via env var `R_TRAVIS`.
Querying Github deploy keys from repo.
✔ Setting active project to '/Users/joe/Code/nlist/nlist'
> Adding deploy keys on GitHub and Travis CI for repo 'nlist'.
──────────────────────────────────────────────────────────────────────────────────────
✓ Added a public deploy key to GitHub for repo 'nlist'.
To interact with the Travis CI API, an API token is required. This is a one-time
procedure. The token will be stored in your home directory in the '.travis'
directory.
> 
Querying API token...
● Opening <https://travis-ci.com/account/preferences>
ℹ  Waiting for API token to appear on the clipboard.
Please paste the API token to the console.

>  Detected token, clearing clipboard.
  Writing Travis CI API token for endpoint '.com' to ~/.travis/config.yml.
✓ Get environment variables for 'poissonconsulting/nlist' on Travis CI.
✓ Adding environment variables for 'poissonconsulting/nlist' on Travis CI.
──────────────────────────────────────────────────────────────────────────────────────
✓ Added a private deploy key to project 'nlist' on Travis CI as secure environment variable 'id_rsa'.
```

And everything appears to be set up correctly at https://github.com/poissonconsulting/nlist.

**Comment by pat-s** [comment] 2019-12-08 09:18
Thanks for the feedback. This will always occur since it is called in `.onLoad()` before you call any function.
I might change it to a "one-time per-session" warning but other than that I do not see this as an error.
It just tells you what it defaults to. This will always be overridden when setting an arg specifically in a fun.

```
Env var 'R_TRAVIS' not set by user. Defaulting to '.org' endpoint.
```

---

```r
travis::use_travis_deploy(endpoint = ".com")
travis: Using Travis endpoint '.com' set via env var `R_TRAVIS`.
```

You do not need to set both, the env var would suffice in this case.

You should only need to set the api token once. Does this message related to the token come back if you run it again?
Regarding your final repo setup, I can't verify this since I do not have access to your private repo tokens :)

Is is clear that it means if `R_TRAVIS` is set?

**Comment by pat-s** [comment] 2019-12-08 12:58
I've optimized the startup message. It is now more descriptive and is only displayed once per session.

**Comment by joethorley** [comment] 2019-12-08 17:26
I removed `R_TRAVIS` from my `.RProfile` file and reran for a new repository and got these messages
```
> travis::use_travis_deploy(endpoint = ".com")
Querying Github deploy keys from repo.
✔ Setting active project to '/Users/joe/Code/err/err'
> Adding deploy keys on GitHub and Travis CI for repo 'err'.
──────────────────────────────────────────────────────────────────────────────────────────────────────────
✓ Added a public deploy key to GitHub for repo 'err'.
travis: Env var 'R_TRAVIS' not set by user. Defaulting to '.org' endpoint. If supplied, the `endpoint`
argument in any `travis_*` function will take precedence. (This message is displayed once per session.)
Querying API token...
● Opening <https://travis-ci.org/account/preferences>
ℹ  Waiting for API token to appear on the clipboard.
Please paste the API token to the console.

>  Detected token, clearing clipboard.
> Existing token detected. Appending new API token.
  Appending Travis CI API token for endpoint '.org' to ~/.travis/config.yml.
✓ Get environment variables for 'poissonconsulting/err' on Travis CI.
✓ Adding environment variables for 'poissonconsulting/err' on Travis CI.
──────────────────────────────────────────────────────────────────────────────────────────────────────────
✓ Added a private deploy key to project 'err' on Travis CI as secure environment variable 'id_rsa'.
```

It took me to the `travis.org` site to get the token - I'm not sure if this is correct either way the message `Appending Travis CI API token for endpoint '.org' to ~/.travis/config.yml.` is confusing.

When I reran I got the following which implies the deploy key comes from .com.
```
> travis::use_travis_deploy(endpoint = ".com")
Querying Github deploy keys from repo.
Deploy key for Travis CI .com already present. No action required.
> 
```

**Comment by pat-s** [comment] 2019-12-08 18:24
Can you please post whats in `~/.travis.config.yml`?

> I removed R_TRAVIS from my .RProfile file

env vars should be set in `.Renviron`, not in `.Rprofile`.

**Comment by pat-s** [comment] 2019-12-08 20:29
> It took me to the travis.org site to get the token - I'm not sure if this is correct either way the message Appending Travis CI API token for endpoint '.org' to ~/.travis/config.yml. is confusing.

This was indeed a regression, thanks for mentioning this. It's fixed now.

**Comment by joethorley** [comment] 2019-12-08 20:42
Yeah I meant `.Renviron`

My ` ~/.travis/config.yml` file is 
```
endpoints:
  https://api.travis-ci.org/:
    access_token: xxxx
 https://api.travis-ci.com/:
   access_token: xxxx
```
I obscured the access tokens.

I'll try with the new version.

**Comment by joethorley** [comment] 2019-12-08 20:51
With the update I get
```
> travis::use_travis_deploy(endpoint = ".com")
Querying Github deploy keys from repo.
✔ Setting active project to '/Users/joe/Code/err/err'
Deploy key for Travis CI .com already present. No action required.
> travis::use_travis_deploy()
Querying Github deploy keys from repo.
Deploy key for Travis CI .com already present. No action required.
```
I then deleted my `~/.travis/config.yml` file and the deploy key on Github and got
```
> travis::use_travis_deploy()
Querying Github deploy keys from repo.
> Adding deploy keys on GitHub and Travis CI for repo 'err'.
──────────────────────────────────────────────────────────────────────────────────────────────────────────
✓ Added a public deploy key to GitHub for repo 'err'.
travis: Using Travis endpoint '.com' set via env var `R_TRAVIS`. If supplied, the `endpoint` argument in
any `travis_*` function will take precedence. (This message is displayed once per session.)
To interact with the Travis CI API, an API token is required. This is a one-time procedure. The token
will be stored in your home directory in the '.travis' directory.
> 
Querying API token...
● Opening <https://travis-ci.com/account/preferences>
ℹ  Waiting for API token to appear on the clipboard.
Please paste the API token to the console.

>  Detected token, clearing clipboard.
  Writing Travis CI API token for endpoint '.com' to ~/.travis/config.yml.
✓ Get environment variables for 'poissonconsulting/err' on Travis CI.
✓ Get environment variables for 'poissonconsulting/err' on Travis CI.
✓ Deleting environment variable with id = '65e880ad-3dec-48c8-81e6-efea27bc1260' for 'poissonconsulting/err' on Travis CI.
✓ Adding environment variables for 'poissonconsulting/err' on Travis CI.
──────────────────────────────────────────────────────────────────────────────────────────────────────────
✓ Added a private deploy key to project 'err' on Travis CI as secure
      environment variable 'id_rsa'.
```

**Comment by pat-s** [comment] 2019-12-08 21:03
Thanks, looks good to me. Let me know if you have further issues.

**Closed** 2019-12-20 02:31 UTC
